#!/usr/bin/env node
// Posts each code question to the Go Playground share API and writes
// the resulting stable URLs to links.js.
// Run: node generate-links.js

const fs   = require('fs');
const https = require('https');
const path  = require('path');

const src = fs.readFileSync(path.join(__dirname, 'questions.js'), 'utf-8');
const QUESTIONS = new Function(src + '; return QUESTIONS;')();

function share(code) {
  return new Promise((resolve, reject) => {
    const body = Buffer.from(code, 'utf-8');
    const req = https.request({
      hostname: 'play.golang.org',
      path: '/share',
      method: 'POST',
      headers: {
        'Content-Type': 'text/plain',
        'Content-Length': body.length,
      },
    }, res => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        if (res.statusCode === 200) {
          resolve(`https://go.dev/play/p/${data.trim()}?v=gotip`);
        } else {
          reject(new Error(`HTTP ${res.statusCode}: ${data.slice(0, 120)}`));
        }
      });
    });
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

function sleep(ms) {
  return new Promise(r => setTimeout(r, ms));
}

async function main() {
  const codeQuestions = QUESTIONS.filter(q => q.code);
  console.log(`Generating playground links for ${codeQuestions.length} questions...`);

  const links = {};
  let ok = 0, fail = 0;

  for (const q of codeQuestions) {
    try {
      const url = await share(q.code);
      links[q.id] = url;
      process.stdout.write(`✅ Q${q.id} ${url}\n`);
      ok++;
    } catch (e) {
      process.stdout.write(`❌ Q${q.id} ${e.message}\n`);
      fail++;
    }
    await sleep(250);
  }

  const out = `// Auto-generated by generate-links.js — do not edit manually.
// Re-run: node generate-links.js
const PLAYGROUND_LINKS = ${JSON.stringify(links, null, 2)};
`;
  fs.writeFileSync(path.join(__dirname, 'links.js'), out);
  console.log(`\n${ok} links written to links.js${fail ? `, ${fail} failed` : ''}`);
}

main();
